const FEED_URL='https://raw.githubusercontent.com/corpzky97/webinarpilot-ai/main/pinoylink/feed.json';
const CANONICAL_ORIGIN='https://pinoylinkhawaii.com';
const DEFAULT_IMAGES={storm:'https://images.unsplash.com/photo-1664383111863-220fb0dbeb03?auto=format&fit=crop&fm=jpg&q=78&w=1400',traffic:'https://images.unsplash.com/photo-1664383111863-220fb0dbeb03?auto=format&fit=crop&fm=jpg&q=78&w=1400',philippines:'https://images.unsplash.com/photo-1564625432203-d3aa35318dc6?auto=format&fit=crop&fm=jpg&q=78&w=1400',immigration:'https://images.unsplash.com/photo-1454496406107-dc34337da8d6?auto=format&fit=crop&fm=jpg&q=78&w=1400',community:'https://images.unsplash.com/photo-1774557936610-ea8aa35019bb?auto=format&fit=crop&fm=jpg&q=78&w=1400',business:'https://images.unsplash.com/photo-1774557936610-ea8aa35019bb?auto=format&fit=crop&fm=jpg&q=78&w=1400',news:'https://images.unsplash.com/photo-1779636813904-7900421432f6?auto=format&fit=crop&fm=jpg&q=78&w=1400'};
const fallback={brand:'PinoyLink Hawaiʻi',tagline:'Your Bridge Between Hawaiʻi and Home.',updated_at:null,edition_type:'latest',edition_date:'',status:'warming_up',lead:{desk:'Newsroom',headline:'PinoyLink Hawaiʻi',summary:'The live newsroom feed is being prepared. Approved stories will appear here automatically.',why_it_matters:'',source_name:'',source_url:'',slug:'',visual_theme:'news',visual_label:'LIVE NEWSROOM'},stories:[]};
function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]))}
function niceDate(v){if(!v)return 'Live feed connected';try{return 'Updated '+new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short',timeZone:'Pacific/Honolulu'}).format(new Date(v))+' HST'}catch{return 'Updated recently'}}
function isExternalSource(url,name){if(!url)return false;try{const u=new URL(url,location.origin);const internalHosts=new Set(['pinoylinkhawaii.com','www.pinoylinkhawaii.com','pinoylink-hawaii.vercel.app']);return !internalHosts.has(u.hostname)&&String(name||'').toLowerCase()!=='pinoylink hawaiʻi'}catch{return false}}
function articleUrl(s){return s&&s.slug?CANONICAL_ORIGIN+'/news/'+encodeURIComponent(s.slug):''}
function themeName(s){return String(s&&s.visual_theme||'news').toLowerCase().replace(/[^a-z-]/g,'')||'news'}
function themeClass(s){return 'theme-'+themeName(s)}
function imageUrl(s){return (s&&s.image_url)||DEFAULT_IMAGES[themeName(s)]||DEFAULT_IMAGES.news}
function mediaHTML(s,label){const img=imageUrl(s);if(!img)return `<span>${esc(label||s?.visual_label||s?.desk||'PinoyLink')}</span>`;const badge=s?.image_caption||'Editorial image';return `<img src="${esc(img)}" alt="${esc(s?.image_alt||s?.headline||'PinoyLink editorial image')}" loading="lazy" decoding="async" referrerpolicy="no-referrer"><div class="media-shade"></div><small class="media-badge">${esc(badge)}</small><span>${esc(label||s?.visual_label||s?.desk||'PinoyLink')}</span>`}
function render(feed){const lead=feed.lead||fallback.lead;document.getElementById('feed-status').textContent=(feed.edition_type?feed.edition_type.toUpperCase()+' EDITION • ':'')+(feed.status||'LIVE');document.getElementById('lead-headline').textContent=lead.headline||fallback.lead.headline;document.getElementById('lead-summary').textContent=lead.summary||fallback.lead.summary;const breaking=document.getElementById('breaking-text');if(breaking)breaking.textContent=lead.headline||fallback.lead.headline;const lv=document.getElementById('lead-visual');if(lv){lv.className='lead-visual '+themeClass(lead)+' has-media';lv.innerHTML=mediaHTML(lead,lead.visual_label||lead.desk||'PinoyLink Hawaiʻi')}const src=document.getElementById('lead-source');const leadUrl=articleUrl(lead);if(leadUrl){src.href=leadUrl;src.textContent='Read full story →';src.removeAttribute('target');src.removeAttribute('rel');src.style.display='inline-block'}else if(isExternalSource(lead.source_url,lead.source_name)){src.href=lead.source_url;src.textContent=lead.source_name?'Source: '+lead.source_name:'Official source';src.target='_blank';src.rel='noopener';src.style.display='inline-block'}else{src.style.display='none'}document.getElementById('updated-at').textContent=niceDate(feed.updated_at);const grid=document.getElementById('story-grid');const stories=Array.isArray(feed.stories)?feed.stories:[];grid.innerHTML=stories.length?stories.slice(0,6).map(s=>{const url=articleUrl(s);const link=url?`<a href="${esc(url)}">Read full story →</a>`:(isExternalSource(s.source_url,s.source_name)?`<a href="${esc(s.source_url)}" target="_blank" rel="noopener">${esc(s.source_name||'Read official source')} →</a>`:'');return `<article class="story"><div class="story-visual ${themeClass(s)} has-media">${mediaHTML(s,s.visual_label||s.desk||'PinoyLink')}</div><div class="story-content"><div class="desk">${esc(s.desk||'Update')}</div><h3>${esc(s.headline||'PinoyLink update')}</h3><p>${esc(s.summary||'')}</p>${link}</div></article>`}).join(''):'<article class="story"><div class="story-content"><div class="desk">Newsroom</div><h3>Live feed is warming up</h3><p>The next approved PinoyLink build will populate this section automatically.</p></div></article>'}
async function load(){try{const r=await fetch(FEED_URL+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('feed '+r.status);render(await r.json())}catch(e){console.warn(e);render(fallback)}}
function setupButtons(){document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(id&&id.length>1){const target=document.querySelector(id);if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'});history.replaceState(null,'',id)}}}));}
function setupSubscribe(){const form=document.getElementById('subscribeForm');if(!form)return;const button=document.getElementById('subscribeSubmit');const status=document.getElementById('subscribeStatus');form.addEventListener('submit',async e=>{e.preventDefault();status.className='form-status full';status.textContent='';if(!form.reportValidity())return;button.disabled=true;button.classList.add('button-busy');const old=button.textContent;button.textContent='Joining…';const submittedEmail=document.getElementById('email').value.trim();try{const payload={email:submittedEmail,first_name:document.getElementById('firstName').value.trim(),island:document.getElementById('island').value,language:document.getElementById('language').value};const r=await fetch('/api/subscribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok){if(r.status===503)throw new Error('Subscription setup is finishing. Please try again shortly.');throw new Error(data.error||'Unable to subscribe right now.')}status.className='form-status full ok';status.innerHTML=`You’re subscribed to PinoyLink Daily. Welcome! <a href="/preferences?email=${encodeURIComponent(submittedEmail)}" style="color:#ffe398">Choose your topics →</a>`;form.reset();document.getElementById('language').value='english';document.getElementById('island').value='other';}catch(err){status.className='form-status full err';status.textContent=err.message||'Unable to subscribe right now.';}finally{button.disabled=false;button.classList.remove('button-busy');button.textContent=old;}})}
load();setInterval(load,5*60*1000);setupButtons();setupSubscribe();