const ARCHIVE_URL='https://raw.githubusercontent.com/corpzky97/webinarpilot-ai/main/pinoylink/archive.json';
const DEFAULT_IMAGES={storm:'https://images.unsplash.com/photo-1664383111863-220fb0dbeb03?auto=format&fit=crop&fm=jpg&q=78&w=1400',traffic:'https://images.unsplash.com/photo-1664383111863-220fb0dbeb03?auto=format&fit=crop&fm=jpg&q=78&w=1400',philippines:'https://images.unsplash.com/photo-1564625432203-d3aa35318dc6?auto=format&fit=crop&fm=jpg&q=78&w=1400',immigration:'https://images.unsplash.com/photo-1454496406107-dc34337da8d6?auto=format&fit=crop&fm=jpg&q=78&w=1400',community:'https://images.unsplash.com/photo-1774557936610-ea8aa35019bb?auto=format&fit=crop&fm=jpg&q=78&w=1400',business:'https://images.unsplash.com/photo-1774557936610-ea8aa35019bb?auto=format&fit=crop&fm=jpg&q=78&w=1400',news:'https://images.unsplash.com/photo-1779636813904-7900421432f6?auto=format&fit=crop&fm=jpg&q=78&w=1400'};
let allStories=[];
function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]))}
function storyUrl(s){return s&&s.slug?'/news/'+encodeURIComponent(s.slug):'#'}
function niceDate(v){if(!v)return '';try{return new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeZone:'Pacific/Honolulu'}).format(new Date(v))}catch{return ''}}
function themeName(s){return String(s.visual_theme||'news').toLowerCase().replace(/[^a-z-]/g,'')||'news'}
function themeClass(s){return 'theme-'+themeName(s)}
function imageUrl(s){return s.image_url||DEFAULT_IMAGES[themeName(s)]||DEFAULT_IMAGES.news}
function mediaHTML(s){const img=imageUrl(s);return `<img src="${esc(img)}" alt="${esc(s.image_alt||s.headline||'PinoyLink editorial image')}" loading="lazy" decoding="async" referrerpolicy="no-referrer"><div class="media-shade"></div><small class="media-badge">${esc(s.image_caption||'Editorial image')}</small><span>${esc(s.visual_label||s.desk||'PinoyLink')}</span>`}
function currentDesk(){return new URLSearchParams(location.search).get('desk')||''}
function setDeskInUrl(desk){const u=new URL(location.href);if(desk)u.searchParams.set('desk',desk);else u.searchParams.delete('desk');history.replaceState(null,'',u)}
function buildFilters(){const desks=[...new Set(allStories.map(s=>s.desk).filter(Boolean))].sort((a,b)=>a.localeCompare(b));const select=document.getElementById('deskFilter');select.innerHTML='<option value="">All desks</option>'+desks.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');const requested=currentDesk();if(requested&&desks.includes(requested))select.value=requested;const chips=['',...desks.slice(0,7)];document.getElementById('chipRow').innerHTML=chips.map(d=>`<button class="archive-chip${select.value===d?' active':''}" data-desk="${esc(d)}">${esc(d||'All')}</button>`).join('');document.querySelectorAll('.archive-chip').forEach(b=>b.addEventListener('click',()=>{select.value=b.dataset.desk||'';setDeskInUrl(select.value);render()}));select.addEventListener('change',()=>{setDeskInUrl(select.value);render()});document.getElementById('archiveSearch').addEventListener('input',render)}
function render(){const q=document.getElementById('archiveSearch').value.trim().toLowerCase();const desk=document.getElementById('deskFilter').value;document.querySelectorAll('.archive-chip').forEach(b=>b.classList.toggle('active',(b.dataset.desk||'')===desk));const filtered=allStories.filter(s=>{if(desk&&s.desk!==desk)return false;if(!q)return true;return [s.headline,s.summary,s.why_it_matters,s.desk,s.visual_label].some(v=>String(v||'').toLowerCase().includes(q))});document.getElementById('archiveCount').textContent=`${filtered.length} stor${filtered.length===1?'y':'ies'}`;const grid=document.getElementById('archiveGrid');grid.innerHTML=filtered.length?filtered.map(s=>`<article class="archive-card"><div class="story-visual ${themeClass(s)} has-media">${mediaHTML(s)}</div><div class="story-content"><div class="desk">${esc(s.desk||'News')}</div><h2>${esc(s.headline||'PinoyLink update')}</h2><p>${esc(s.summary||'')}</p><small class="muted">${esc(niceDate(s.published_at))}</small><a href="${esc(storyUrl(s))}">Read full story →</a></div></article>`).join(''):'<div class="empty-state">No matching PinoyLink stories yet. Try another search or desk.</div>'}
async function load(){const grid=document.getElementById('archiveGrid');try{const r=await fetch(ARCHIVE_URL+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('archive '+r.status);const data=await r.json();allStories=Array.isArray(data.stories)?data.stories:[];allStories.sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0));buildFilters();render()}catch(e){console.warn(e);document.getElementById('archiveCount').textContent='Archive unavailable';grid.innerHTML='<div class="empty-state">The story archive is temporarily unavailable. Please return to the homepage for the latest edition.</div>'}}
load();