const FEED_URL='https://raw.githubusercontent.com/corpzky97/webinarpilot-ai/main/pinoylink/feed.json';
const CANONICAL_ORIGIN='https://pinoylinkhawaii.com';
const DEFAULT_IMAGES={storm:'https://images.unsplash.com/photo-1664383111863-220fb0dbeb03?auto=format&fit=crop&fm=jpg&q=82&w=1800',traffic:'https://images.unsplash.com/photo-1664383111863-220fb0dbeb03?auto=format&fit=crop&fm=jpg&q=82&w=1800',philippines:'https://images.unsplash.com/photo-1564625432203-d3aa35318dc6?auto=format&fit=crop&fm=jpg&q=82&w=1800',immigration:'https://images.unsplash.com/photo-1454496406107-dc34337da8d6?auto=format&fit=crop&fm=jpg&q=82&w=1800',community:'https://images.unsplash.com/photo-1774557936610-ea8aa35019bb?auto=format&fit=crop&fm=jpg&q=82&w=1800',business:'https://images.unsplash.com/photo-1774557936610-ea8aa35019bb?auto=format&fit=crop&fm=jpg&q=82&w=1800',news:'https://images.unsplash.com/photo-1779636813904-7900421432f6?auto=format&fit=crop&fm=jpg&q=82&w=1800'};
function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]))}
function slugFromLocation(){const q=new URLSearchParams(location.search).get('slug');if(q)return q;const parts=location.pathname.split('/').filter(Boolean);return parts[0]==='news'&&parts[1]?parts[1]:''}
function niceDate(v){if(!v)return '';try{return new Intl.DateTimeFormat('en-US',{dateStyle:'long',timeStyle:'short',timeZone:'Pacific/Honolulu'}).format(new Date(v))+' HST'}catch{return String(v)}}
function paraHTML(body){if(Array.isArray(body))return body.map(p=>`<p>${esc(p)}</p>`).join('');return String(body||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('')}
function themeName(item){return String(item?.visual_theme||'news').toLowerCase().replace(/[^a-z-]/g,'')||'news'}
function visualClass(theme){const allowed=new Set(['storm','traffic','philippines','community','immigration','business','news']);return allowed.has(theme)?'visual-'+theme:'visual-news'}
function imageUrl(item){return item.image_url||DEFAULT_IMAGES[themeName(item)]||DEFAULT_IMAGES.news}
function setMeta(id,value){const el=document.getElementById(id);if(el)el.setAttribute('content',value||'')}
function applySEO(item){const slug=item.slug||slugFromLocation();const url=CANONICAL_ORIGIN+'/news/'+encodeURIComponent(slug);const title=item.headline||'PinoyLink Hawaiʻi Story';const desc=item.summary||'Verified community news from PinoyLink Hawaiʻi.';const img=imageUrl(item);const canonical=document.getElementById('canonical-link');if(canonical)canonical.href=url;setMeta('og-title',title);setMeta('og-description',desc);setMeta('og-url',url);setMeta('og-image',img);setMeta('twitter-title',title);setMeta('twitter-description',desc);setMeta('twitter-image',img);const jsonld=document.getElementById('article-jsonld');if(jsonld){jsonld.textContent=JSON.stringify({'@context':'https://schema.org','@type':'NewsArticle',headline:title,description:desc,datePublished:item.published_at||undefined,dateModified:item.published_at||undefined,mainEntityOfPage:url,image:img?[img]:undefined,articleSection:item.desk||'News',publisher:{'@type':'Organization',name:'PinoyLink Hawaiʻi',url:CANONICAL_ORIGIN+'/'},isBasedOn:item.source_url||undefined})}}
function renderArticle(item,feed){document.title=(item.headline||'PinoyLink Hawaiʻi')+' | PinoyLink Hawaiʻi';document.querySelector('meta[name="description"]').setAttribute('content',item.summary||'PinoyLink Hawaiʻi verified community news.');applySEO(item);document.getElementById('article-desk').textContent=item.desk||'PinoyLink newsroom';document.getElementById('article-title').textContent=item.headline||'PinoyLink Hawaiʻi';document.getElementById('article-dek').textContent=item.summary||'';document.getElementById('article-meta').textContent=[feed.edition_type?feed.edition_type.toUpperCase()+' EDITION':'',niceDate(item.published_at||feed.updated_at)].filter(Boolean).join(' • ');document.getElementById('article-body').innerHTML=paraHTML(item.body||item.summary||'');document.getElementById('article-why').textContent=item.why_it_matters||'This update may affect daily plans, travel, family decisions or community awareness.';const src=document.getElementById('article-source');if(item.source_url){src.href=item.source_url;src.textContent=(item.source_name||'Official source')+' →'}else{src.closest('.source-box').style.display='none'};const disclaimer=document.getElementById('article-disclaimer');if(item.disclaimer){disclaimer.textContent=item.disclaimer;disclaimer.style.display='block'}else{disclaimer.style.display='none'};const vis=document.getElementById('article-visual');vis.className='article-visual '+visualClass(themeName(item))+' has-media';const old=vis.querySelector('.article-photo');if(old)old.remove();const img=document.createElement('img');img.className='article-photo';img.src=imageUrl(item);img.alt=item.image_alt||item.headline||'PinoyLink editorial image';img.loading='eager';img.decoding='async';img.referrerPolicy='no-referrer';vis.prepend(img);document.getElementById('visual-kicker').textContent=(item.desk||'PINOYLINK').toUpperCase();document.getElementById('visual-headline').textContent=(item.visual_label||item.headline||'VERIFIED UPDATE').toUpperCase();let credit=document.getElementById('media-credit');if(!credit){credit=document.createElement('div');credit.id='media-credit';credit.className='media-credit';vis.insertAdjacentElement('afterend',credit)}credit.textContent=item.image_credit?`Photo: ${item.image_credit}${item.image_caption?' • '+item.image_caption:''}`:(item.image_caption||'Editorial image used for context; not a documentary image of the reported event.');const url=CANONICAL_ORIGIN+'/news/'+encodeURIComponent(item.slug||slugFromLocation());document.getElementById('share-facebook').href='https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(url);document.getElementById('copy-link').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(url);document.getElementById('copy-status').textContent='Link copied.'}catch{document.getElementById('copy-status').textContent=url}})}
function renderMissing(){document.getElementById('article-title').textContent='Story not found';document.getElementById('article-dek').textContent='This PinoyLink story may have moved or is not yet published.';document.getElementById('article-meta').textContent='';document.getElementById('article-body').innerHTML='<p>Please return to the homepage for the latest approved stories.</p>';document.getElementById('why-box').style.display='none';document.querySelector('.source-box').style.display='none'}
async function load(){try{const r=await fetch(FEED_URL+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('feed '+r.status);const feed=await r.json();const slug=slugFromLocation();const all=[feed.lead,...(Array.isArray(feed.stories)?feed.stories:[])].filter(Boolean);const item=all.find(x=>x.slug===slug);if(item)renderArticle(item,feed);else renderMissing()}catch(e){console.warn(e);renderMissing()}}
load();