const FEED_URL='https://raw.githubusercontent.com/corpzky97/webinarpilot-ai/main/pinoylink/feed.json';
function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]))}
function slugFromLocation(){const q=new URLSearchParams(location.search).get('slug');if(q)return q;const parts=location.pathname.split('/').filter(Boolean);return parts[0]==='news'&&parts[1]?parts[1]:''}
function niceDate(v){if(!v)return '';try{return new Intl.DateTimeFormat('en-US',{dateStyle:'long',timeStyle:'short',timeZone:'Pacific/Honolulu'}).format(new Date(v))+' HST'}catch{return String(v)}}
function paraHTML(body){if(Array.isArray(body))return body.map(p=>`<p>${esc(p)}</p>`).join('');return String(body||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('')}
function visualClass(theme){const allowed=new Set(['storm','traffic','philippines','community','immigration','business','news']);return allowed.has(theme)?'visual-'+theme:'visual-news'}
function renderArticle(item,feed){document.title=(item.headline||'PinoyLink Hawaiʻi')+' | PinoyLink Hawaiʻi';document.querySelector('meta[name="description"]').setAttribute('content',item.summary||'PinoyLink Hawaiʻi verified community news.');document.getElementById('article-desk').textContent=item.desk||'PinoyLink newsroom';document.getElementById('article-title').textContent=item.headline||'PinoyLink Hawaiʻi';document.getElementById('article-dek').textContent=item.summary||'';document.getElementById('article-meta').textContent=[feed.edition_type?feed.edition_type.toUpperCase()+' EDITION':'',niceDate(item.published_at||feed.updated_at)].filter(Boolean).join(' • ');document.getElementById('article-body').innerHTML=paraHTML(item.body||item.summary||'');document.getElementById('article-why').textContent=item.why_it_matters||'This update may affect daily plans, travel, family decisions or community awareness.';const src=document.getElementById('article-source');if(item.source_url){src.href=item.source_url;src.textContent=(item.source_name||'Official source')+' →'}else{src.closest('.source-box').style.display='none'};const disclaimer=document.getElementById('article-disclaimer');if(item.disclaimer){disclaimer.textContent=item.disclaimer;disclaimer.style.display='block'}else{disclaimer.style.display='none'};const vis=document.getElementById('article-visual');vis.className='article-visual '+visualClass(item.visual_theme);document.getElementById('visual-kicker').textContent=(item.desk||'PINOYLINK').toUpperCase();document.getElementById('visual-headline').textContent=(item.visual_label||item.headline||'VERIFIED UPDATE').toUpperCase();const url=location.href;document.getElementById('share-facebook').href='https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(url);document.getElementById('copy-link').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(url);document.getElementById('copy-status').textContent='Link copied.'}catch{document.getElementById('copy-status').textContent=url}})}
function renderMissing(){document.getElementById('article-title').textContent='Story not found';document.getElementById('article-dek').textContent='This PinoyLink story may have moved or is not yet published.';document.getElementById('article-meta').textContent='';document.getElementById('article-body').innerHTML='<p>Please return to the homepage for the latest approved stories.</p>';document.getElementById('why-box').style.display='none';document.querySelector('.source-box').style.display='none'}
async function load(){try{const r=await fetch(FEED_URL+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('feed '+r.status);const feed=await r.json();const slug=slugFromLocation();const all=[feed.lead,...(Array.isArray(feed.stories)?feed.stories:[])].filter(Boolean);const item=all.find(x=>x.slug===slug);if(item)renderArticle(item,feed);else renderMissing()}catch(e){console.warn(e);renderMissing()}}
load();